# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.no.bpe
canonical: http://hl7.no/fhir/ig/bpe
name: BPExperimental
title: "Best Practice Experimental"
description: Implementasjonsguide for å teste dokumentasjon for Best Practice - eksperimentell
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2025+
releaseLabel: ci-build
jurisdiction: urn:iso:std:iso:3166#NO "Norway"
publisher:
  name: HL7 Norge
  url: https://www.hl7.no
dependencies:
  hl7.fhir.no.basis: 2.2.0

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Artifacts: artifacts.html
  TOC: toc.html
